#!/bin/sh

echo "+ starting execloadkey"
echo "+ original ssh command : $SSH_ORIGINAL_COMMAND"

KEY=$(echo "$SSH_ORIGINAL_COMMAND" | sed -e "s/^ssh-add \/ssh\/keys\/\(.*\)$/\1/")

echo "+ key to load: $KEY"
if [ ! -z "$KEY" -a -r "$KEY" ]; then
    ssh-add /ssh/keys/$KEY
    exit 0
fi

echo "+ go away nasty"
exit 1